- id: pylint-boolean-naming
  name: pylint-boolean-naming
  entry: pylint
  language: python
  types: [python]
  additional_dependencies: [pylint]
  args: [
    "--load-plugins=pylint-checkers:boolean_naming_checker"
    "--init-hook=import sys;  import os; sys.path.append('.')"
  ]